### ISSUE TITLE
在1.6.1版本中无法取消自动编译

### ISSUE THREAD

**Issue by tangqiu0205** [devkanro/intellij-protobuf-plugin#110]
去掉勾选状态,但右下角应用还是处于灰色状态, 点击确定. 再次进入页面, 自动编译还是处于启用状态.

经测试 idea 和 goland 都设置不成功.

<img width="271" alt="image" src="https://user-images.githubusercontent.com/37826977/173178854-0f6ae3ef-19a6-45f1-8d56-871fcdf2bbd8.png">

<img width="312" alt="image" src="https://user-images.githubusercontent.com/37826977/173178867-a47662b0-3b10-45d4-a180-65e27150e80e.png">

**Comment by devkanro** [comment]
我自己试了一下，灰色状态好像只是有点慢，但是还是能亮  
灰色状态保存应该是不起作用的  
另外可以看看你的工程目录下 .idea 文件夹，protobuf.xml 的内容吗

**Comment by tangqiu0205** [comment]
protobuf.xml
<img width="512" alt="image" src="https://user-images.githubusercontent.com/37826977/173208413-23cc215a-3410-4720-afcb-75079ebaf770.png">

protoeditor.xml
<img width="776" alt="image" src="https://user-images.githubusercontent.com/37826977/173208426-b699e99a-56eb-405b-bd60-e4230a8fff3e.png">

**Comment by devkanro** [comment]
<img width="440" alt="截屏2022-06-13 上午10 27 04" src="https://user-images.githubusercontent.com/9367842/173268663-8dfd60cb-8763-41be-9466-36b4f0054b5f.png">
奇怪了，我用 IDEA 是可以的，保存了之后配置也变了

**Comment by devkanro** [comment]
反过来试试看，你把
```xml
<option name="autoDecompile" value="false" />
```
放到 protobuf.xml 看看

**Comment by tangqiu0205** [comment]
手动加上这一段, 项目打开确实没有自动编译了. 不过按钮还是打开状态.
<img width="626" alt="image" src="https://user-images.githubusercontent.com/37826977/173280687-1231584c-603e-4e8c-b98d-2051f7a3deae.png">

**Comment by mingming-cn** [comment]
我也遇到这个问题了，而且这个自动反编译出来的proto还是有问题的，导致一些proto引用出错。

**Comment by devkanro** [comment]
@mingming-cn 能具体描述一下反编译出来的 proto 有什么的引用错误吗？
你也是用 GoLand 吗？取消了自动反编译也不行？

**Comment by mingming-cn** [comment]
> @mingming-cn 能具体描述一下反编译出来的 proto 有什么的引用错误吗？ 你也是用 GoLand 吗？取消了自动反编译也不行？

### 使用环境
OS: Macos 12.4
IDE: Golang 2022.1.4、GoLand 2022.1.3 均有问题

### 问题情况
- 尝试过卸载重装问题依旧。
- 通过UI界面上的 ”Auto-detect and decompile from binary descriptor“ 选项无法取消。
- 目前手动在protobuf.xml中添加了<option name="autoDecompile" value="false" /> 可以取消反编译了。

### 反编译问题
- 根据反编译出的文件里Source判断应该是从本地机器上的  GOPATH/pkg/mod/*.pb.go 之类的文件中反编译出的proto文件。
- 反编译出的 *.proto 文件与 *.pb.go 文件里的内容不匹配，比如：缺少很多内容或只有package xxx 并没有实际的 proto定义内容。

google/api/field_behavior.proto
只反编译出 FieldBehavior ，实际还有很多内容缺失了
![Snipaste_2022-07-26_15-14-52](https://user-images.githubusercontent.com/37921196/180946619-47921a6b-77c2-4182-81ea-d7c6361ad31f.png)

protoc-gen-openapiv2/options/annotations.proto
只有 package 和 import 信息，其它全部缺失
![Snipaste_2022-07-26_15-15-25](https://user-images.githubusercontent.com/37921196/180946634-d7dfdda4-e39d-44f5-8324-da2311e9e3fa.png)

**Comment by devkanro** [comment]
@mingming-cn 
我复现了选择框的这个问题，下个版本应该能解决

另外反编译的问题，我现在只反编译了 Message 和 Enum，对于 Extension 还没，下个版本应该也能加上。

**Comment by devkanro** [comment]
@mingming-cn @tangqiu0205 

- #116

在上面的链接中可以下载修复版本，此版本为 2022.2 版本构建，我强制让他支持 2022.1 可能会出现一些问题，但是应该可以用来测试本 issue 中提到的两个 bug。

要是有时间的话，麻烦帮我测试一下。

**Comment by mingming-cn** [comment]
@devkanro  1.6.21-EAP 版本， ”Auto-detect and decompile from binary descriptor“  选项可以正常使用了。

**Comment by devkanro** [comment]
@mingming-cn 
感谢 🙏，另外能看看现在反编译出来的 proto 有没有 extension 了嘛

**Comment by tangqiu0205** [comment]
可以正常使用了, 不过插件有报错.

````com.intellij.diagnostic.PluginException: Cannot create class io.kanro.idea.plugin.protobuf.lang.actions.ProtobufActionGroup (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Protobuf, id=io.kanro.idea.plugin.protobuf, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\GoLand2022.1\plugins\IntelliJ Protobuf Language Plugin, version=1.6.21-EAP, package=null, isBundled=false), packagePrefix=null, instanceId=59, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:884)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:901)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:201)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertGroupStub(ActionManagerImpl.java:230)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:523)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:512)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:409)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:365)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:343)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doGetChildren(ActionUpdater.java:663)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$1(ActionUpdater.java:113)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:176)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$2(ActionUpdater.java:113)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$getGroupChildren$21(ActionUpdater.java:464)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.getGroupChildren(ActionUpdater.java:463)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:456)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroup(ActionUpdater.java:260)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$12(ActionUpdater.java:321)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$13(ActionUpdater.java:339)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1152)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$tryRunReadActionAndCancelBeforeWrite$17(ActionUpdater.java:371)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.tryRunReadActionAndCancelBeforeWrite(ActionUpdater.java:367)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$14(ActionUpdater.java:339)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:365)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$15(ActionUpdater.java:338)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:241)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:214)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NoSuchMethodError: 'void com.intellij.openapi.actionSystem.Presentation.setHideGroupIfEmpty(boolean)'
	at io.kanro.idea.plugin.protobuf.lang.actions.ProtobufActionGroup.<init>(ProtobufActionGroup.kt:7)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:845)
	... 45 more

**Comment by devkanro** [comment]
@tangqiu0205 
ok，这个就是兼容问题

**Comment by mingming-cn** [comment]
> @mingming-cn 感谢 🙏，另外能看看现在反编译出来的 proto 有没有 extension 了嘛

extension 也有了

**Comment by devkanro** [comment]
Fixed in [v1.6.20](https://github.com/devkanro/intellij-protobuf-plugin/releases/tag/v1.6.20)
