### ISSUE TITLE
java.lang.IllegalArgumentException: fromIndex(7) > toIndex(6)

### ISSUE THREAD

**Issue by BorzdeG** [devkanro/intellij-protobuf-plugin#118]
plugin version: 1.6.21-EAP
GoLang: 2022.2 (Build #GO-222.3345.118)

```
java.lang.IllegalArgumentException: fromIndex(7) > toIndex(6)
	at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:509)
	at java.base/java.util.ArrayList.subList(ArrayList.java:1108)
	at com.intellij.psi.util.QualifiedName.subQualifiedName(QualifiedName.java:194)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler.findGroup(ProtobufDecompiler.kt:280)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler.access$findGroup(ProtobufDecompiler.kt:9)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler$generate$4.invoke(ProtobufDecompiler.kt:140)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler$generate$4.invoke(ProtobufDecompiler.kt:130)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler.stackWrapper(ProtobufDecompiler.kt:292)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler.generate(ProtobufDecompiler.kt:130)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler$generate$7$1.invoke(ProtobufDecompiler.kt:193)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler$generate$7$1.invoke(ProtobufDecompiler.kt:191)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufCodeBuilder.block(ProtobufCodeBuilder.kt:63)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler.generate(ProtobufDecompiler.kt:191)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler$decompile$1.invoke(ProtobufDecompiler.kt:57)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler$decompile$1.invoke(ProtobufDecompiler.kt:11)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufCodeBuilderKt.buildProtobuf(ProtobufCodeBuilder.kt:81)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler.decompile(ProtobufDecompiler.kt:11)
	at io.kanro.idea.plugin.protobuf.decompile.DecompiledFileManager.findFile(DecompiledFileManager.kt:106)
	at io.kanro.idea.plugin.protobuf.golang.ExtensionKt.decompile(Extension.kt:17)
	at io.kanro.idea.plugin.protobuf.golang.GoDecompileService$runActivity$1$1.run(GoDecompileService.kt:35)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:915)
	at io.kanro.idea.plugin.protobuf.golang.GoDecompileService$runActivity$$inlined$runBackgroundableTask$1.run(progress.kt:38)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by devkanro** [comment]
This is a bug for protobuf decompiler when decompile the group field, I will try to fix it.

By the way, the 1.6.21 is out, you can use this version for more bug fixed(not include this issue).

**Comment by BorzdeG** [comment]
Yes, I saw that the latest version was released, but it has not yet appeared in my GoLand marketplace... :(

**Comment by devkanro** [comment]
After some check, this bug only happens with extension group field, can you provide the generated go file for this sense?

**Comment by BorzdeG** [comment]
I suspect it was related to this proto, but the bug hasn't reproduced yet...
The "money/..." package is located outside the project and included in the settings as "external import root" with common=true

```
syntax = "proto3";

package calculator_fee_api;

import "money/crypto-and-fiat.proto";
import "money/money.proto";

option go_package = "XXX/backend/go/protobuf/calculator-api/fee";

service FeeService {
	rpc GetFee (Fee.Request) returns (Fee.Response);
}

message Fee {
	message Request {
		money.Money item_price = 1;
		uint32 quantity = 2;
		Type type = 3;
	}

	message Response {
		money.CryptoAndFiat price = 1;
		string description = 2;
	}

	enum Type {
		TYPE_UNSPECIFIED = 0;
		TYPE_PERCENTAGE_OF_THE_COST = 1;
	}
}
```

```
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: calculator/fee/fee.proto

package fee

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	money "XXX2/api/public/money"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Fee_Type int32

const (
	Fee_TYPE_UNSPECIFIED            Fee_Type = 0
	Fee_TYPE_PERCENTAGE_OF_THE_COST Fee_Type = 1
)

// Enum value maps for Fee_Type.
var (
	Fee_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_PERCENTAGE_OF_THE_COST",
	}
	Fee_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED":            0,
		"TYPE_PERCENTAGE_OF_THE_COST": 1,
	}
)

func (x Fee_Type) Enum() *Fee_Type {
	p := new(Fee_Type)
	*p = x
	return p
}

func (x Fee_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Fee_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_calculator_fee_fee_proto_enumTypes[0].Descriptor()
}

func (Fee_Type) Type() protoreflect.EnumType {
	return &file_calculator_fee_fee_proto_enumTypes[0]
}

func (x Fee_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Fee_Type.Descriptor instead.
func (Fee_Type) EnumDescriptor() ([]byte, []int) {
	return file_calculator_fee_fee_proto_rawDescGZIP(), []int{0, 0}
}

type Fee struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Fee) Reset() {
	*x = Fee{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculator_fee_fee_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fee) ProtoMessage() {}

func (x *Fee) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_fee_fee_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fee.ProtoReflect.Descriptor instead.
func (*Fee) Descriptor() ([]byte, []int) {
	return file_calculator_fee_fee_proto_rawDescGZIP(), []int{0}
}

type Fee_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemPrice *money.Money `protobuf:"bytes,1,opt,name=item_price,json=itemPrice,proto3" json:"item_price,omitempty"`
	Quantity  uint32       `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Type      Fee_Type     `protobuf:"varint,3,opt,name=type,proto3,enum=calculator_fee_api.Fee_Type" json:"type,omitempty"`
}

func (x *Fee_Request) Reset() {
	*x = Fee_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculator_fee_fee_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fee_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fee_Request) ProtoMessage() {}

func (x *Fee_Request) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_fee_fee_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fee_Request.ProtoReflect.Descriptor instead.
func (*Fee_Request) Descriptor() ([]byte, []int) {
	return file_calculator_fee_fee_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Fee_Request) GetItemPrice() *money.Money {
	if x != nil {
		return x.ItemPrice
	}
	return nil
}

func (x *Fee_Request) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Fee_Request) GetType() Fee_Type {
	if x != nil {
		return x.Type
	}
	return Fee_TYPE_UNSPECIFIED
}

type Fee_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price       *money.CryptoAndFiat `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Description string               `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Fee_Response) Reset() {
	*x = Fee_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculator_fee_fee_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fee_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fee_Response) ProtoMessage() {}

func (x *Fee_Response) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_fee_fee_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fee_Response.ProtoReflect.Descriptor instead.
func (*Fee_Response) Descriptor() ([]byte, []int) {
	return file_calculator_fee_fee_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Fee_Response) GetPrice() *money.CryptoAndFiat {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *Fee_Response) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_calculator_fee_fee_proto protoreflect.FileDescriptor

var file_calculator_fee_fee_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x66, 0x65, 0x65,
	0x2f, 0x66, 0x65, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x63, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x66, 0x65, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x1a, 0x1b,
	0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x2f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2d, 0x61, 0x6e, 0x64,
	0x2d, 0x66, 0x69, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x6d, 0x6f, 0x6e,
	0x65, 0x79, 0x2f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa5,
	0x02, 0x0a, 0x03, 0x46, 0x65, 0x65, 0x1a, 0x84, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2b, 0x0a, 0x0a, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x2e, 0x4d,
	0x6f, 0x6e, 0x65, 0x79, 0x52, 0x09, 0x69, 0x74, 0x65, 0x6d, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x30, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x63, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x66, 0x65, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x46,
	0x65, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x1a, 0x58, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x6f, 0x6e, 0x65, 0x79,
	0x2e, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x41, 0x6e, 0x64, 0x46, 0x69, 0x61, 0x74, 0x52, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3d, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1f, 0x0a, 0x1b, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x45,
	0x52, 0x43, 0x45, 0x4e, 0x54, 0x41, 0x47, 0x45, 0x5f, 0x4f, 0x46, 0x5f, 0x54, 0x48, 0x45, 0x5f,
	0x43, 0x4f, 0x53, 0x54, 0x10, 0x01, 0x32, 0x59, 0x0a, 0x0a, 0x46, 0x65, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x46, 0x65, 0x65, 0x12, 0x1f,
	0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x66, 0x65, 0x65, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x46, 0x65, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x20, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x66, 0x65, 0x65,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x65, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x3f, 0x5a, 0x3d, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x68, 0x79, 0x70, 0x65,
	0x72, 0x66, 0x6c, 0x65, 0x78, 0x2f, 0x63, 0x74, 0x6e, 0x66, 0x74, 0x2f, 0x62, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x66,
	0x65, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_calculator_fee_fee_proto_rawDescOnce sync.Once
	file_calculator_fee_fee_proto_rawDescData = file_calculator_fee_fee_proto_rawDesc
)

func file_calculator_fee_fee_proto_rawDescGZIP() []byte {
	file_calculator_fee_fee_proto_rawDescOnce.Do(func() {
		file_calculator_fee_fee_proto_rawDescData = protoimpl.X.CompressGZIP(file_calculator_fee_fee_proto_rawDescData)
	})
	return file_calculator_fee_fee_proto_rawDescData
}

var file_calculator_fee_fee_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_calculator_fee_fee_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_calculator_fee_fee_proto_goTypes = []interface{}{
	(Fee_Type)(0),               // 0: calculator_fee_api.Fee.Type
	(*Fee)(nil),                 // 1: calculator_fee_api.Fee
	(*Fee_Request)(nil),         // 2: calculator_fee_api.Fee.Request
	(*Fee_Response)(nil),        // 3: calculator_fee_api.Fee.Response
	(*money.Money)(nil),         // 4: money.Money
	(*money.CryptoAndFiat)(nil), // 5: money.CryptoAndFiat
}
var file_calculator_fee_fee_proto_depIdxs = []int32{
	4, // 0: calculator_fee_api.Fee.Request.item_price:type_name -> money.Money
	0, // 1: calculator_fee_api.Fee.Request.type:type_name -> calculator_fee_api.Fee.Type
	5, // 2: calculator_fee_api.Fee.Response.price:type_name -> money.CryptoAndFiat
	2, // 3: calculator_fee_api.FeeService.GetFee:input_type -> calculator_fee_api.Fee.Request
	3, // 4: calculator_fee_api.FeeService.GetFee:output_type -> calculator_fee_api.Fee.Response
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_calculator_fee_fee_proto_init() }
func file_calculator_fee_fee_proto_init() {
	if File_calculator_fee_fee_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_calculator_fee_fee_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fee); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calculator_fee_fee_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fee_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calculator_fee_fee_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fee_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_calculator_fee_fee_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calculator_fee_fee_proto_goTypes,
		DependencyIndexes: file_calculator_fee_fee_proto_depIdxs,
		EnumInfos:         file_calculator_fee_fee_proto_enumTypes,
		MessageInfos:      file_calculator_fee_fee_proto_msgTypes,
	}.Build()
	File_calculator_fee_fee_proto = out.File
	file_calculator_fee_fee_proto_rawDesc = nil
	file_calculator_fee_fee_proto_goTypes = nil
	file_calculator_fee_fee_proto_depIdxs = nil
}
```

**Comment by devkanro** [comment]
You can see a line mark for description line.

If this file cause the bug, click it will 100% reproduce this exception.

![](https://user-images.githubusercontent.com/9367842/128091217-37aa0766-914f-4464-9365-a1f16ef9b5da.png
)

**Comment by BorzdeG** [comment]
I don't have that mark

<img width="563" alt="image" src="https://user-images.githubusercontent.com/2332528/181703679-55faca77-a962-42f4-8be6-75e5f23ff786.png">

**Comment by BorzdeG** [comment]
But, on the other hand, the error was reproduced if the generated go-file was opened when opening the project

**Comment by devkanro** [comment]
Yes, it will be reproduced when decompiling some protos which include group extension field

**Comment by devkanro** [comment]
I fix it in d30ba2ca552bba3175cd0d76e9d859c9e35c05e3, I will release the 1.6.22 soon

There are the change log

### Fixed

- Fix group extension field decompile error
- Fix group field annotation always fail
- Fix group extension field range check
- Fix decompile line marker is not shown

### Changed

- Make auto-decompile default as disable

**Comment by devkanro** [comment]
As you can see, this project don't has test code, I known tests is very useful to keep plugin high usability, but I have no more time to focus on it.

I am using this plugin on Java/Kotlin project, If you got any bug or suggestion on working Go Project, feel free to open an issue.

**Comment by devkanro** [comment]
By the way, recommend [my gRPC debugging tool](https://github.com/ButterCam/Mediator) to you, if you using the gRPC.

This tool just support paintext(non-tls) request now, but I will add tls support soon.
