### ISSUE TITLE
Plugin not compatible with IntelliJ IDEA 2023.1 (Community Edition)

### ISSUE THREAD

**Issue by EpariNigam** [devkanro/intellij-protobuf-plugin#178]
Cannot process toolwindow io.kanro.idea.plugin.protobuf.toolwindow

```
java.lang.NoClassDefFoundError: com/fasterxml/jackson/dataformat/yaml/YAMLMapper
	at io.kanro.idea.plugin.protobuf.buf.project.BufFileManager.<init>(BufFileManager.kt:62)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:91)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:1041)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:43)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:39)
	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:154)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance$lambda$1(BaseComponentAdapter.kt:133)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:132)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:92)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:714)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:670)
	at io.kanro.idea.plugin.protobuf.buf.ui.toolwindow.BufToolWindowFactory.shouldBeAvailable(BufToolWindowFactory.kt:27)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.beanToTask(ToolWindowSetInitializer.kt:264)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.beanToTask(ToolWindowSetInitializer.kt:250)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.access$beanToTask(ToolWindowSetInitializer.kt:1)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt$computeToolWindowBeans$1.invoke(ToolWindowSetInitializer.kt:279)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt$computeToolWindowBeans$1.invoke(ToolWindowSetInitializer.kt:275)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.computeToolWindowBeans$lambda$0(ToolWindowSetInitializer.kt:275)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:299)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.computeToolWindowBeans(ToolWindowSetInitializer.kt:275)
	at com.intellij.openapi.project.impl.ProjectFrameAllocatorKt$initFrame$1$taskListDeferred$1.invokeSuspend(ProjectFrameAllocator.kt:364)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(ProjectImpl@73352759), StandaloneCoroutine{Cancelled}@15b6fc44, Dispatchers.Default]
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.dataformat.yaml.YAMLMapper PluginClassLoader(plugin=PluginDescriptor(name=Protobuf, id=io.kanro.idea.plugin.protobuf, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IdeaIC2023.1/plugins/IntelliJ Protobuf Language Plugin, version=1.7.11, package=null, isBundled=false), packagePrefix=null, instanceId=159, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 33 more

```

**Comment by EpariNigam** [comment]
The plugin io.kanro.idea.plugin.protobuf failed to save settings and has been disabled. Please restart IntelliJ IDEA

**Comment by EpariNigam** [comment]
Hey @devkanro any update on this. Because every time I start idea, I have to disable plugin and reenable it.

**Comment by devkanro** [comment]
Sorry for the delay, I'll check the compatibility of the plugin on the IC this week

**Comment by devkanro** [comment]
@EpariNigam Please check the #182

**Comment by EpariNigam** [comment]
Hey Thanks @devkanro for quick update. Let me check this and get back to you.

**Comment by EpariNigam** [comment]
Hey @devkanro thanks, it is working now and the earlier error is gone. I am finally able to open project and it is loading.

But, I am getting a new error.

```
com.intellij.diagnostic.PluginException: Cannot create class io.kanro.idea.plugin.protobuf.buf.annotator.BufLintAnnotator (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Protobuf, id=io.kanro.idea.plugin.protobuf, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IdeaIC2023.1/plugins/IntelliJ Protobuf Language Plugin, version=1.7.12-EAP, package=null, isBundled=false), packagePrefix=null, instanceId=174, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1034)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1051)
	at com.intellij.serviceContainer.LazyExtensionInstance.createInstance(LazyExtensionInstance.java:55)
	at com.intellij.serviceContainer.LazyExtensionInstance.getInstance(LazyExtensionInstance.java:44)
	at com.intellij.serviceContainer.BaseKeyedLazyInstance.getInstance(BaseKeyedLazyInstance.java:38)
	at com.intellij.openapi.util.KeyedExtensionCollector.instantiate(KeyedExtensionCollector.java:177)
	at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensionsFromExtensionPoint(KeyedExtensionCollector.java:164)
	at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:139)
	at com.intellij.lang.LanguageExtension.buildExtensions(LanguageExtension.java:147)
	at com.intellij.lang.LanguageExtension.buildExtensions(LanguageExtension.java:16)
	at com.intellij.openapi.util.KeyedExtensionCollector.forKey(KeyedExtensionCollector.java:111)
	at com.intellij.lang.LanguageExtension.collectAllForLanguage(LanguageExtension.java:125)
	at com.intellij.lang.LanguageExtension.allForLanguage(LanguageExtension.java:116)
	at com.intellij.lang.LanguageExtension.allForLanguageOrAny(LanguageExtension.java:160)
	at com.intellij.lang.ExternalLanguageAnnotators.allForFile(ExternalLanguageAnnotators.java:23)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPassFactory.externalAnnotatorsDefined(ExternalToolPassFactory.java:37)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPassFactory.createHighlightingPass(ExternalToolPassFactory.java:29)
	at com.intellij.codeInsight.daemon.impl.TextEditorHighlightingPassRegistrarImpl.instantiatePasses(TextEditorHighlightingPassRegistrarImpl.java:188)
	at com.intellij.codeInsight.daemon.impl.TextEditorBackgroundHighlighter.getPasses(TextEditorBackgroundHighlighter.java:75)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$submitInBackground$23(DaemonCodeAnalyzerImpl.java:1077)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:891)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:69)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$submitInBackground$24(DaemonCodeAnalyzerImpl.java:1066)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.submitInBackground(DaemonCodeAnalyzerImpl.java:1063)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$queuePassesCreation$19(DaemonCodeAnalyzerImpl.java:1028)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.ClassCastException: class com.fasterxml.jackson.module.kotlin.KotlinModule cannot be cast to class com.fasterxml.jackson.databind.Module (com.fasterxml.jackson.module.kotlin.KotlinModule is in unnamed module of loader com.intellij.util.lang.PathClassLoader @21a06946; com.fasterxml.jackson.databind.Module is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @a2559f4)
	at io.kanro.idea.plugin.protobuf.buf.annotator.BufLintAnnotator.<init>(BufLintAnnotator.kt:27)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:993)
	... 35 more

```

**Comment by devkanro** [comment]
@EpariNigam Please check the #182 again

**Comment by EpariNigam** [comment]
Sure. Will check and update you.

**Comment by EpariNigam** [comment]
Hey @devkanro , it is working fine.

**Comment by devkanro** [comment]
OK, I will release this version soon
