### ISSUE TITLE
Plugin Exception Abandoned AnnotationBuilder in IntelliJ IDEA 2023.2.1

### ISSUE THREAD

**Issue by nofarius** [devkanro/intellij-protobuf-plugin#195]
The following error keeps occurring in IntelliJ 2023.2.1

Everything still seems to work, and the annotation is still applied in the UI, but I get a notification with this error every time I change something in a proto file that has a warning or error, which results in a lot of error notifications!

```java
com.intellij.diagnostic.PluginException: Abandoned AnnotationBuilder - its 'create()' method was never called: Builder{message='Field name should be snake_case', myCurrentElement={com.intellij.model.psi.impl.PsiSymbolReferenceServiceImpl$$Lambda$7659/0x0000007002e2a6c8=PsiCachedValueImpl{com.intellij.model.psi.impl.PsiSymbolReferenceServiceImpl$$Lambda$7659/0x0000007002e2a6c8@4cbebf91}, io.kanro.idea.plugin.protobuf.lang.psi.ExtensionKt$$Lambda$8599/0x000000700363d228=PsiCachedValueImpl{io.kanro.idea.plugin.protobuf.lang.psi.ExtensionKt$$Lambda$8599/0x000000700363d228@132a4ec6}} (class io.kanro.idea.plugin.protobuf.lang.psi.impl.ProtobufFieldDefinitionImpl), myCurrentAnnotator=io.kanro.idea.plugin.protobuf.lang.annotator.ProtobufAnnotator@3b029ffd, severity=WARNING, range=(implicit)(5180,5226)} [Plugin: io.kanro.idea.plugin.protobuf]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:99)
	at com.intellij.codeInsight.daemon.impl.B.assertAnnotationCreated(B.java:333)
	at com.intellij.codeInsight.daemon.impl.AnnotationHolderImpl.assertAllAnnotationsCreated(AnnotationHolderImpl.java:269)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:323)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:286)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:234)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:95)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:390)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:77)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:24)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:386)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:377)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:376)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:352)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:207)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:350)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:190)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.IllegalStateException: Abandoned AnnotationBuilder - its 'create()' method was never called: Builder{message='Field name should be snake_case', myCurrentElement={com.intellij.model.psi.impl.PsiSymbolReferenceServiceImpl$$Lambda$7659/0x0000007002e2a6c8=PsiCachedValueImpl{com.intellij.model.psi.impl.PsiSymbolReferenceServiceImpl$$Lambda$7659/0x0000007002e2a6c8@4cbebf91}, io.kanro.idea.plugin.protobuf.lang.psi.ExtensionKt$$Lambda$8599/0x000000700363d228=PsiCachedValueImpl{io.kanro.idea.plugin.protobuf.lang.psi.ExtensionKt$$Lambda$8599/0x000000700363d228@132a4ec6}} (class io.kanro.idea.plugin.protobuf.lang.psi.impl.ProtobufFieldDefinitionImpl), myCurrentAnnotator=io.kanro.idea.plugin.protobuf.lang.annotator.ProtobufAnnotator@3b029ffd, severity=WARNING, range=(implicit)(5180,5226)}
	at com.intellij.codeInsight.daemon.impl.B.assertAnnotationCreated(B.java:332)
	... 29 more
```

**Comment by devkanro** [comment]
I cannot reproduce this bug. Could you please provide the proto file after desensitization?

**Comment by nofarius** [comment]
There must have been something temporarily wrong with my intellij, I was getting this error constantly, but after restarting my computer haven't seen it once 🤷‍♂️
