### ISSUE TITLE
kotlin.NotImplementedError: An operation is not implemented.

### ISSUE THREAD

**Issue by CyJaySong** [devkanro/intellij-protobuf-plugin#224]
```
kotlin.NotImplementedError: An operation is not implemented.
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler.fieldType(ProtobufDecompiler.kt:270)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler.access$fieldType(ProtobufDecompiler.kt:9)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler$generate$4.invoke(ProtobufDecompiler.kt:176)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler$generate$4.invoke(ProtobufDecompiler.kt:153)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler.stackWrapper(ProtobufDecompiler.kt:338)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler.generate(ProtobufDecompiler.kt:153)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler$generate$4$1$2$1.invoke(ProtobufDecompiler.kt:169)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler$generate$4$1$2$1.invoke(ProtobufDecompiler.kt:164)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufCodeBuilder.block(ProtobufCodeBuilder.kt:66)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler$generate$4.invoke(ProtobufDecompiler.kt:164)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler$generate$4.invoke(ProtobufDecompiler.kt:153)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler.stackWrapper(ProtobufDecompiler.kt:338)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler.generate(ProtobufDecompiler.kt:153)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler$generate$3$1$1.invoke(ProtobufDecompiler.kt:128)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler$generate$3$1$1.invoke(ProtobufDecompiler.kt:116)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufCodeBuilder.block(ProtobufCodeBuilder.kt:66)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler$generate$3.invoke(ProtobufDecompiler.kt:116)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler$generate$3.invoke(ProtobufDecompiler.kt:113)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler.stackWrapper(ProtobufDecompiler.kt:338)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler.generate(ProtobufDecompiler.kt:113)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler$decompile$1.invoke(ProtobufDecompiler.kt:63)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler$decompile$1.invoke(ProtobufDecompiler.kt:11)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufCodeBuilderKt.buildProtobuf(ProtobufCodeBuilder.kt:87)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler.decompile(ProtobufDecompiler.kt:11)
	at io.kanro.idea.plugin.protobuf.decompile.DecompiledFileManager.findFile(DecompiledFileManager.kt:114)
	at io.kanro.idea.plugin.protobuf.golang.ExtensionKt.decompile(Extension.kt:18)
	at io.kanro.idea.plugin.protobuf.golang.GoDecompileService$execute$2$1.run(GoDecompileService.kt:37)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:878)
	at io.kanro.idea.plugin.protobuf.golang.GoDecompileService$execute$$inlined$runBackgroundableTask$1.run(progress.kt:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:132)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:484)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:248)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:248)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:498)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by devkanro** [comment]
Group feature of Protobuf2 will not supported in decompiling
