### ISSUE TITLE
v2.0.1会莫名报错

### ISSUE THREAD

**Issue by nethibernate** [devkanro/intellij-protobuf-plugin#277]
没有找到报错的规律，intellj的protobuf和gRpc我都已经disable了。
附件的文件是报错信息，因为太长了，所以只能用文件方式。
[exception.log](https://github.com/user-attachments/files/17128611/exception.log)

**Comment by godcong** [comment]
启动有异常:
```
kotlin.NotImplementedError: An operation is not implemented.
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler.fieldType(ProtobufDecompiler.kt:270)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler.generate$lambda$31(ProtobufDecompiler.kt:176)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler.stackWrapper(ProtobufDecompiler.kt:338)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler.generate(ProtobufDecompiler.kt:153)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler.generate$lambda$31$lambda$30$lambda$29$lambda$28(ProtobufDecompiler.kt:169)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufCodeBuilder.block(ProtobufCodeBuilder.kt:66)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler.generate$lambda$31(ProtobufDecompiler.kt:164)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler.stackWrapper(ProtobufDecompiler.kt:338)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler.generate(ProtobufDecompiler.kt:153)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler.generate$lambda$21$lambda$20$lambda$19(ProtobufDecompiler.kt:128)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufCodeBuilder.block(ProtobufCodeBuilder.kt:66)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler.generate$lambda$21(ProtobufDecompiler.kt:116)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler.stackWrapper(ProtobufDecompiler.kt:338)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler.generate(ProtobufDecompiler.kt:113)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler.decompile$lambda$7(ProtobufDecompiler.kt:63)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufCodeBuilderKt.buildProtobuf(ProtobufCodeBuilder.kt:87)
	at io.kanro.idea.plugin.protobuf.decompile.ProtobufDecompiler.decompile(ProtobufDecompiler.kt:11)
	at io.kanro.idea.plugin.protobuf.decompile.DecompiledFileManager.findFile(DecompiledFileManager.kt:114)
	at io.kanro.idea.plugin.protobuf.golang.ExtensionKt.decompile(Extension.kt:18)
	at io.kanro.idea.plugin.protobuf.golang.GoDecompileService$execute$2$1.run(GoDecompileService.kt:37)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction$lambda$2(AnyThreadWriteThreadingSupport.kt:217)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:264)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:217)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:847)
	at io.kanro.idea.plugin.protobuf.golang.GoDecompileService$execute$$inlined$runBackgroundableTask$1.run(progress.kt:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:477)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:528)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:249)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:221)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:49)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:220)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:249)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:501)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:466)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:92)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:92)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:97)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:92)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$19(ProgressRunner.java:464)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by devkanro** [comment]
Fixed in 2.0.2
