### ISSUE TITLE
ClassNotFoundException when opening a proto file

### ISSUE THREAD

**Issue by davidkarlsson** [devkanro/intellij-protobuf-plugin#278]
Using JetBrains Rider 2024.2.5 with plugin version 2.0.1 I get an error report with the following stack trace whenever I open a proto file for the first time since I loaded a solution:

```
com.intellij.diagnostic.PluginException: io.kanro.idea.plugin.protobuf.lang.reference.ProtobufSymbolReferenceContributor PluginClassLoader(plugin=PluginDescriptor(name=Protobuf, id=io.kanro.idea.plugin.protobuf, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\Rider2024.2\plugins\IntelliJ Protobuf Language Plugin, version=2.0.1, package=null, isBundled=false), packagePrefix=null, state=active, parents=PluginDescriptor(name=Markdown, id=org.intellij.plugins.markdown, moduleName=intellij.markdown.xml, descriptorPath=intellij.markdown.xml.xml, path=C:\Program Files\JetBrains\Rider\plugins\markdown, version=242.22855.90, package=org.intellij.plugins.markdown.xml, isBundled=true), PluginDescriptor(name=Markdown, id=org.intellij.plugins.markdown, moduleName=intellij.markdown.spellchecker, descriptorPath=intellij.markdown.spellchecker.xml, path=C:\Program Files\JetBrains\Rider\plugins\markdown, version=242.22855.90, package=org.intellij.plugins.markdown.spellchecker, isBundled=true), PluginDescriptor(name=Markdown, id=org.intellij.plugins.markdown, moduleName=intellij.markdown.model, descriptorPath=intellij.markdown.model.xml, path=C:\Program Files\JetBrains\Rider\plugins\markdown, version=242.22855.90, package=org.intellij.plugins.markdown.model, isBundled=true), PluginDescriptor(name=Markdown, id=org.intellij.plugins.markdown, moduleName=intellij.markdown.images, descriptorPath=intellij.markdown.images.xml, path=C:\Program Files\JetBrains\Rider\plugins\markdown, version=242.22855.90, package=org.intellij.plugins.markdown.images, isBundled=true), PluginDescriptor(name=Markdown, id=org.intellij.plugins.markdown, moduleName=intellij.markdown.frontmatter.yaml, descriptorPath=intellij.markdown.frontmatter.yaml.xml, path=C:\Program Files\JetBrains\Rider\plugins\markdown, version=242.22855.90, package=org.intellij.plugins.markdown.frontmatter.yaml, isBundled=true), PluginDescriptor(name=Markdown, id=org.intellij.plugins.markdown, moduleName=intellij.markdown.frontmatter.toml, descriptorPath=intellij.markdown.frontmatter.toml.xml, path=C:\Program Files\JetBrains\Rider\plugins\markdown, version=242.22855.90, package=org.intellij.plugins.markdown.frontmatter.toml, isBundled=true), PluginDescriptor(name=Markdown, id=org.intellij.plugins.markdown, moduleName=intellij.markdown.frontmatter, descriptorPath=intellij.markdown.frontmatter.xml, path=C:\Program Files\JetBrains\Rider\plugins\markdown, version=242.22855.90, package=org.intellij.plugins.markdown.frontmatter, isBundled=true), PluginDescriptor(name=Markdown, id=org.intellij.plugins.markdown, moduleName=intellij.markdown.fenceInjection, descriptorPath=intellij.markdown.fenceInjection.xml, path=C:\Program Files\JetBrains\Rider\plugins\markdown, version=242.22855.90, package=org.intellij.plugins.markdown.fenceInjection, isBundled=true), PluginDescriptor(name=HTTP Client, id=com.jetbrains.restClient, moduleName=intellij.restClient/microservicesUI, descriptorPath=intellij.restClient.microservicesUI.xml, path=C:\Program Files\JetBrains\Rider\plugins\restClient, version=242.22855.90, package=com.intellij.httpClient.microservices, isBundled=true), PluginDescriptor(name=HTTP Client, id=com.jetbrains.restClient, moduleName=intellij.restClient/jsonPath, descriptorPath=intellij.restClient.jsonPath.xml, path=C:\Program Files\JetBrains\Rider\plugins\restClient, version=242.22855.90, package=com.intellij.httpClient.jsonPath, isBundled=true), PluginDescriptor(name=HTTP Client, id=com.jetbrains.restClient, moduleName=intellij.restClient/javaScript, descriptorPath=intellij.restClient.javaScript.xml, path=C:\Program Files\JetBrains\Rider\plugins\restClient, version=242.22855.90, package=com.intellij.httpClient.js, isBundled=true), PluginDescriptor(name=HTTP Client, id=com.jetbrains.restClient, moduleName=intellij.restClient/intelliLangInJs, descriptorPath=intellij.restClient.intelliLangInJs.xml, path=C:\Program Files\JetBrains\Rider\plugins\restClient, version=242.22855.90, package=com.intellij.httpClient.injection.javaScript, isBundled=true), PluginDescriptor(name=HTTP Client, id=com.jetbrains.restClient, moduleName=intellij.httpClient.injection.graphql, descriptorPath=intellij.httpClient.injection.graphql.xml, path=C:\Program Files\JetBrains\Rider\plugins\restClient, version=242.22855.90, package=com.intellij.httpClient.injection.graphql, isBundled=true), PluginDescriptor(name=HTTP Client, id=com.jetbrains.restClient, moduleName=intellij.restClient/intelliLang, descriptorPath=intellij.restClient.intelliLang.xml, path=C:\Program Files\JetBrains\Rider\plugins\restClient, version=242.22855.90, package=com.intellij.httpClient.injection, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.impl, descriptorPath=intellij.platform.vcs.impl.xml, path=C:\Program Files\JetBrains\Rider\lib, version=242.22855.90, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.log.impl, descriptorPath=intellij.platform.vcs.log.impl.xml, path=C:\Program Files\JetBrains\Rider\lib, version=242.22855.90, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.dvcs.impl, descriptorPath=intellij.platform.vcs.dvcs.impl.xml, path=C:\Program Files\JetBrains\Rider\lib, version=242.22855.90, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.collaborationTools, descriptorPath=intellij.platform.collaborationTools.xml, path=C:\Program Files\JetBrains\Rider\lib, version=242.22855.90, package=null, isBundled=true), PluginDescriptor(name=Markdown, id=org.intellij.plugins.markdown, descriptorPath=plugin.xml, path=C:\Program Files\JetBrains\Rider\plugins\markdown, version=242.22855.90, package=org.intellij.plugins.markdown, isBundled=true), PluginDescriptor(name=HTTP Client, id=com.jetbrains.restClient, descriptorPath=plugin.xml, path=C:\Program Files\JetBrains\Rider\plugins\restClient, version=242.22855.90, package=com.intellij.httpClient, isBundled=true), )
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:943)
	at com.intellij.serviceContainer.LazyExtensionInstance.createInstance(LazyExtensionInstance.java:57)
	at com.intellij.serviceContainer.LazyExtensionInstance.getInstance(LazyExtensionInstance.java:46)
	at com.intellij.serviceContainer.BaseKeyedLazyInstance.getInstance(BaseKeyedLazyInstance.java:38)
	at com.intellij.openapi.util.KeyedExtensionCollector.instantiate(KeyedExtensionCollector.java:200)
	at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensionsFromExtensionPoint(KeyedExtensionCollector.java:162)
	at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:135)
	at com.intellij.lang.LanguageExtension.buildExtensions(LanguageExtension.java:134)
	at com.intellij.lang.LanguageExtension.buildExtensions(LanguageExtension.java:19)
	at com.intellij.openapi.util.KeyedExtensionCollector.forKey(KeyedExtensionCollector.java:112)
	at com.intellij.lang.LanguageExtension.collectAllForLanguage(LanguageExtension.java:125)
	at com.intellij.lang.LanguageExtension.allForLanguage(LanguageExtension.java:118)
	at com.intellij.lang.LanguageExtension.allForLanguageOrAny(LanguageExtension.java:146)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.createRegistrar(ReferenceProvidersRegistryImpl.java:62)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getRegistrar(ReferenceProvidersRegistryImpl.java:99)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:120)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.lambda$getReferencesFromProviders$0(ReferenceProvidersRegistry.java:44)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:173)
	at com.intellij.psi.impl.PsiCachedValueImpl$Direct.doCompute(PsiCachedValueImpl.kt:77)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:236)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:236)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:237)
	at com.intellij.psi.impl.PsiCachedValueImpl$Direct.getValue(PsiCachedValueImpl.kt:81)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:83)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:170)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:136)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:42)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:35)
	at io.kanro.idea.plugin.protobuf.lang.psi.proto.mixin.ProtobufStringValueMixin.getReferences(ProtobufStringValueMixin.kt:17)
	at io.kanro.idea.plugin.protobuf.lang.psi.proto.mixin.ProtobufStringValueMixin.getReference(ProtobufStringValueMixin.kt:13)
	at io.kanro.idea.plugin.protobuf.aip.annotator.AipAnnotator$annotate$1.visitStringValue(AipAnnotator.kt:26)
	at io.kanro.idea.plugin.protobuf.lang.psi.proto.impl.ProtobufStringValueImpl.accept(ProtobufStringValueImpl.java:21)
	at io.kanro.idea.plugin.protobuf.lang.psi.proto.impl.ProtobufStringValueImpl.accept(ProtobufStringValueImpl.java:26)
	at io.kanro.idea.plugin.protobuf.aip.annotator.AipAnnotator.annotate(AipAnnotator.kt:23)
	at com.intellij.codeInsight.daemon.impl.AnnotationHolderImpl.runAnnotatorWithContext(AnnotationHolderImpl.java:216)
	at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.lambda$runAnnotator$2(AnnotatorRunner.java:129)
	at com.intellij.codeInsight.daemon.impl.AnnotationSessionImpl.computeWithSession(AnnotationSessionImpl.java:87)
	at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.runAnnotator(AnnotatorRunner.java:119)
	at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.lambda$runAnnotatorsAsync$0(AnnotatorRunner.java:66)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:279)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.lambda$runAnnotatorsAsync$1(AnnotatorRunner.java:66)
	at com.intellij.concurrency.client.ClientIdPropagation.captureClientIdInProcessor$lambda$7(ClientIdPropagation.kt:63)
	at com.intellij.concurrency.ApplierCompleter.processArrayItem(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.processArray(ApplierCompleter.java:196)
	at com.intellij.concurrency.ApplierCompleter.execAll(ApplierCompleter.java:166)
	at com.intellij.concurrency.ApplierCompleter.lambda$exec$0(ApplierCompleter.java:105)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$2(ApplierCompleter.java:148)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:159)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapAndRun$1(ApplierCompleter.java:140)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.executeByImpatientReader(AnyThreadWriteThreadingSupport.kt:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.concurrency.ApplierCompleter.wrapAndRun(ApplierCompleter.java:140)
	at com.intellij.concurrency.ApplierCompleter.exec(ApplierCompleter.java:108)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.lang.ClassNotFoundException: io.kanro.idea.plugin.protobuf.lang.reference.ProtobufSymbolReferenceContributor PluginClassLoader(plugin=PluginDescriptor(name=Protobuf, id=io.kanro.idea.plugin.protobuf, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\Rider2024.2\plugins\IntelliJ Protobuf Language Plugin, version=2.0.1, package=null, isBundled=false), packagePrefix=null, state=active, parents=PluginDescriptor(name=Markdown, id=org.intellij.plugins.markdown, moduleName=intellij.markdown.xml, descriptorPath=intellij.markdown.xml.xml, path=C:\Program Files\JetBrains\Rider\plugins\markdown, version=242.22855.90, package=org.intellij.plugins.markdown.xml, isBundled=true), PluginDescriptor(name=Markdown, id=org.intellij.plugins.markdown, moduleName=intellij.markdown.spellchecker, descriptorPath=intellij.markdown.spellchecker.xml, path=C:\Program Files\JetBrains\Rider\plugins\markdown, version=242.22855.90, package=org.intellij.plugins.markdown.spellchecker, isBundled=true), PluginDescriptor(name=Markdown, id=org.intellij.plugins.markdown, moduleName=intellij.markdown.model, descriptorPath=intellij.markdown.model.xml, path=C:\Program Files\JetBrains\Rider\plugins\markdown, version=242.22855.90, package=org.intellij.plugins.markdown.model, isBundled=true), PluginDescriptor(name=Markdown, id=org.intellij.plugins.markdown, moduleName=intellij.markdown.images, descriptorPath=intellij.markdown.images.xml, path=C:\Program Files\JetBrains\Rider\plugins\markdown, version=242.22855.90, package=org.intellij.plugins.markdown.images, isBundled=true), PluginDescriptor(name=Markdown, id=org.intellij.plugins.markdown, moduleName=intellij.markdown.frontmatter.yaml, descriptorPath=intellij.markdown.frontmatter.yaml.xml, path=C:\Program Files\JetBrains\Rider\plugins\markdown, version=242.22855.90, package=org.intellij.plugins.markdown.frontmatter.yaml, isBundled=true), PluginDescriptor(name=Markdown, id=org.intellij.plugins.markdown, moduleName=intellij.markdown.frontmatter.toml, descriptorPath=intellij.markdown.frontmatter.toml.xml, path=C:\Program Files\JetBrains\Rider\plugins\markdown, version=242.22855.90, package=org.intellij.plugins.markdown.frontmatter.toml, isBundled=true), PluginDescriptor(name=Markdown, id=org.intellij.plugins.markdown, moduleName=intellij.markdown.frontmatter, descriptorPath=intellij.markdown.frontmatter.xml, path=C:\Program Files\JetBrains\Rider\plugins\markdown, version=242.22855.90, package=org.intellij.plugins.markdown.frontmatter, isBundled=true), PluginDescriptor(name=Markdown, id=org.intellij.plugins.markdown, moduleName=intellij.markdown.fenceInjection, descriptorPath=intellij.markdown.fenceInjection.xml, path=C:\Program Files\JetBrains\Rider\plugins\markdown, version=242.22855.90, package=org.intellij.plugins.markdown.fenceInjection, isBundled=true), PluginDescriptor(name=HTTP Client, id=com.jetbrains.restClient, moduleName=intellij.restClient/microservicesUI, descriptorPath=intellij.restClient.microservicesUI.xml, path=C:\Program Files\JetBrains\Rider\plugins\restClient, version=242.22855.90, package=com.intellij.httpClient.microservices, isBundled=true), PluginDescriptor(name=HTTP Client, id=com.jetbrains.restClient, moduleName=intellij.restClient/jsonPath, descriptorPath=intellij.restClient.jsonPath.xml, path=C:\Program Files\JetBrains\Rider\plugins\restClient, version=242.22855.90, package=com.intellij.httpClient.jsonPath, isBundled=true), PluginDescriptor(name=HTTP Client, id=com.jetbrains.restClient, moduleName=intellij.restClient/javaScript, descriptorPath=intellij.restClient.javaScript.xml, path=C:\Program Files\JetBrains\Rider\plugins\restClient, version=242.22855.90, package=com.intellij.httpClient.js, isBundled=true), PluginDescriptor(name=HTTP Client, id=com.jetbrains.restClient, moduleName=intellij.restClient/intelliLangInJs, descriptorPath=intellij.restClient.intelliLangInJs.xml, path=C:\Program Files\JetBrains\Rider\plugins\restClient, version=242.22855.90, package=com.intellij.httpClient.injection.javaScript, isBundled=true), PluginDescriptor(name=HTTP Client, id=com.jetbrains.restClient, moduleName=intellij.httpClient.injection.graphql, descriptorPath=intellij.httpClient.injection.graphql.xml, path=C:\Program Files\JetBrains\Rider\plugins\restClient, version=242.22855.90, package=com.intellij.httpClient.injection.graphql, isBundled=true), PluginDescriptor(name=HTTP Client, id=com.jetbrains.restClient, moduleName=intellij.restClient/intelliLang, descriptorPath=intellij.restClient.intelliLang.xml, path=C:\Program Files\JetBrains\Rider\plugins\restClient, version=242.22855.90, package=com.intellij.httpClient.injection, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.impl, descriptorPath=intellij.platform.vcs.impl.xml, path=C:\Program Files\JetBrains\Rider\lib, version=242.22855.90, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.log.impl, descriptorPath=intellij.platform.vcs.log.impl.xml, path=C:\Program Files\JetBrains\Rider\lib, version=242.22855.90, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.dvcs.impl, descriptorPath=intellij.platform.vcs.dvcs.impl.xml, path=C:\Program Files\JetBrains\Rider\lib, version=242.22855.90, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.collaborationTools, descriptorPath=intellij.platform.collaborationTools.xml, path=C:\Program Files\JetBrains\Rider\lib, version=242.22855.90, package=null, isBundled=true), PluginDescriptor(name=Markdown, id=org.intellij.plugins.markdown, descriptorPath=plugin.xml, path=C:\Program Files\JetBrains\Rider\plugins\markdown, version=242.22855.90, package=org.intellij.plugins.markdown, isBundled=true), PluginDescriptor(name=HTTP Client, id=com.jetbrains.restClient, descriptorPath=plugin.xml, path=C:\Program Files\JetBrains\Rider\plugins\restClient, version=242.22855.90, package=com.intellij.httpClient, isBundled=true), )
	at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1464)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:935)
	... 70 more
```

**Comment by nethibernate** [comment]
I have the same issue too.

**Comment by devkanro** [comment]
Fixed in 2.0.2
